ContactBook/Models/AddContactViewModel.cs
namespace ContactBook.Models
{
    public class AddContactViewModel
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public bool Favorite { get; set; }
    }
}

ContactBook/Models/Entities/Contact.cs
namespace ContactBook.Models.Entities
{
    public class Contact
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public bool Favorite { get; set; }
    }
}

ContactBook/Models/ErrorViewModel.cs
namespace ContactBook.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ContactBook/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace ContactBook.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult About()
        {
            return View();
        }
    }
}

ContactBook/Controllers/ContactsController.cs
using ContactBook;
using ContactBook.Data;
using ContactBook.Models;
using ContactBook.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using System.Diagnostics.Contracts;

namespace ContactBook.Controllers
{
    public class ContactsController : Controller
    {
        private readonly ApplicationDBContext dbContext;

        public ContactsController(ApplicationDBContext DbContext)
        {
            dbContext = DbContext;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddContactViewModel viewModel) 
        {
            var Contact = new Contact
            {
                Name = viewModel.Name,
                Email = viewModel.Email,
                Phone = viewModel.Phone,
                Favorite = viewModel.Favorite
            };
            await dbContext.Contacts.AddAsync(Contact);
            await dbContext.SaveChangesAsync();

            return RedirectToAction("List", "Contacts");
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var Contacts = await dbContext.Contacts.ToListAsync();

            return View(Contacts);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var Contact = await dbContext.Contacts.FindAsync(id);

            return View(Contact);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Contact viewModel)
        {
            var Contact = await dbContext.Contacts.FindAsync(viewModel.Id);
            {
                if(Contact != null)
                {
                    Contact.Name = viewModel.Name;
                    Contact.Email = viewModel.Email;
                    Contact.Phone = viewModel.Phone;
                    Contact.Favorite = viewModel.Favorite;

                    await dbContext.SaveChangesAsync();
                }

                return RedirectToAction("List", "Contacts");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Contact viewModel)
        {
            var Contact = await dbContext.Contacts.AsNoTracking().FirstOrDefaultAsync(x => x.Id == viewModel.Id);
            if(Contact != null)
            {
                dbContext.Contacts.Remove(viewModel);
                await dbContext.SaveChangesAsync();

            }
            return RedirectToAction("List", "Contacts");

        }
    }
}

ContactBook/Controllers/PrivacyController.cs
using Microsoft.AspNetCore.Mvc;

namespace ContactBook.Controllers
{
    public class PrivacyController : Controller
    {
        public IActionResult Privacy()
        {
            return View();
        }
    }
}

ContactBook/Views/About/About.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContactBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/styles.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/ContactBook.styles.css" asp-append-version="true" />
    
</head>
<body>
<header class="text-center py-3 ">
    <h1>About Our Website</h1>
</header>
<main class="container my-5">
    <section class="mb-5">
        <h2>Technologies Used</h2>
        <div class="d-flex flex-wrap justify-content-around">
            <div class="tech-item">
                <img src="~/image/csharp.png" alt="C# Logo" class="tech-logo" />
                <p>C#</p>
            </div>
            <div class="tech-item">
                <img src="~/image/aspnetcore.png"
                     alt="ASP.NET Core 7 Logo"
                     class="tech-logo" />
                <p>ASP.NET 7</p>
            </div>
            <div class="tech-item">
                <img src="~/image/entityframework.png"
                     alt="Entity Framework Core Logo"
                     class="tech-logo" />
                <p>EF Core 7</p>
            </div>
            <div class="tech-item">
                <img src="~/image/sqlserver.png" alt="SQL Server Logo" class="tech-logo" />
                <p>SQL Server</p>
            </div>
            <div class="tech-item">
                <img src="~/image/html.png" alt="HTML Logo" class="tech-logo" />
                <p>HTML</p>
            </div>
            <div class="tech-item">
                <img src="~/image/css.png" alt="CSS Logo" class="tech-logo" />
                <p>CSS</p>
            </div>
            <div class="tech-item">
                <img src="~/image/bootstrap.png" alt="Bootstrap Logo" class="tech-logo" />
                <p>Bootstrap</p>
            </div>
        </div>
    </section>
    <section>
        <h2>Developer Details</h2>
        <div class="developer-info">
            <p><strong>Name:</strong> Ratnesh Kumar</p>
            <p><strong>Email:</strong> ratneshx175@gmail.com</p>
            <p>
                <strong>LinkedIn:</strong>
                <a href="https://www.linkedin.com/in/ratneshx175/" target="_blank">
                    <img src="~/image/linkedin.png"
                         alt="LinkedIn Logo"
                         class="linkedin-logo" />
                    linkedin.com/in/ratneshx175
                </a>
            </p>
        </div>
    </section>
    <br />
</main>
</body>
</html>

ContactBook/Views/Contacts/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ContactBook.Models.AddContactViewModel


<h1>Add Contact</h1>

<form method="post">
<div class="mt-3">
    <label class="form_label">Name</label> 
    <input type="text" class="form_control" asp-for="Name"/>
</div>

<div class="mt-3">
    <label class="form_label">Email</label>
    <input type="email" class="form_control" asp-for="Email"/>
</div>

<div class="mt-3">
    <label class="form_label">Phone</label>
        <input type="text" class="form_control" maxlength="10" pattern="\d{10}" title="Please enter exactly 10 digits" asp-for="Phone" required/>
        <small class="form-text text-muted">Please enter a 10-digit phone number.</small>
</div>

<div class="mt-3">
    <input type="checkbox" class="form-check-input" id="Favorite" asp-for="Favorite" />
    <label class="form-check-label" for="Favorite">Favorite</label>
</div>

<div class="mt-3">
    <button type="submit" class="btn btn-primary">Save</button>
</div>
</form>

ContactBook/Views/Contacts/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ContactBook.Models.Entities.Contact

<h1>Edit Contact</h1>

@if (Model is null)
{
    <p>No Contact was found with this Id</p>
}

else
{

    <form method="post">
        <div class="mt-3">
            <label class="form_label">Id</label>
            <input type="text" class="form_control" asp-for="Id" readonly />
        </div>

        <div class="mt-3">
            <label class="form_label">Name</label>
            <input type="text" class="form_control" asp-for="Name" />
        </div>

        <div class="mt-3">
            <label class="form_label">Email</label>
            <input type="email" class="form_control" asp-for="Email" />
        </div>

        <div class="mt-3">
            <label class="form_label">Phone</label>
            <input type="text" class="form_control" maxlength="10" pattern="\d{10}" title="Please enter exactly 10 digits" asp-for="Phone" required />
            <small class="form-text text-muted">Please enter a 10-digit phone number.</small>
        </div>

        <div class="mt-3">
            <input type="checkbox" class="form-check-input" id="Favorite" asp-for="Favorite" />
            <label class="form-check-label" for="Favorite">Favorite</label>
        </div>

        <div class="mt-3">
            <button type="submit" class="btn btn-primary">Save</button>

            <button type="submit" class="btn btn-danger ms-3" asp-action="Delete" asp-controller="Contacts">Delete</button>
        </div>


    </form>
}

ContactBook/Views/Contacts/List.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model List<ContactBook.Models.Entities.Contact>


<div class="Contacth1">

    <h1>Contacts</h1>

    <a class="btn " id="AddButton" asp-controller="Contacts" asp-action="Add"><h4>+ Add</h4></a>
</div>


<table class="table">
    <thead>
        <tr>
            <th class="hide-on-small1">Id</th>
            <th>Name</th>
            <th class="hide-on-small2">Email</th>
            <th>Phone</th>
            <th></th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach(var Contact in Model)
        {
            <tr>
                <td class="hide-on-small1">@Contact.Id</td>
                <td>@Contact.Name</td>
                <td class="hide-on-small2">@Contact.Email</td>
                <td>@Contact.Phone</td>
                <td>
                    <a class="btn btn-primary" asp-controller="Contacts" asp-action="Edit" asp-route-id="@Contact.Id">Edit</a>
                </td>

                <td>
                    <form method="post">
                        <div>
                            <button type="submit" class="btn btn-danger ms-3" asp-action="Delete" asp-controller="Contacts" asp-route-id="@Contact.Id">Delete</button>
                        </div>
                    </form>
                </td>
            </tr>
        }
    </tbody>

</table>

ContactBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContactBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ContactBook.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Contacts" asp-action="List"><h3>ContactBook</h3></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacts" asp-action="List">All Contacts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-dark" >
        <div class="container">
            &copy; 2024 - ContactBook - <a asp-area="" asp-controller="Privacy" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>